### ISSUE TITLE
syntax error, unexpected tLABEL, expecting ')'

### ISSUE THREAD

**Issue by supar** [akiko-pusu/redmine_issue_templates#92]
Plugin version 0.1.4

ActionView::Template::Error (/home/redmine/redmine/plugins/redmine_issue_templates/app/models/issue_template_setting.rb:6: syntax error, unexpected tLABEL, expecting ')'
    def apply_template_to_child_projects(project_id:)

/home/redmine/redmine/plugins/redmine_issue_templates/app/models/issue_template_setting.rb:11: syntax error, unexpected tLABEL, expecting ')'
    def unapply_template_from_child_projects(project_id:)

Environment:
  Redmine version                2.6.10.stable
  Ruby version                   1.9.3-p194 (2012-04-20) [x86_64-linux]
  Rails version                  3.2.22.2
  Environment                    production
  Database adapter               Mysql2

**Comment by akiko-pusu** [comment]
Hi, I'm sorry to inconvenience you.
Did you get source code from Release page?
(https://github.com/akiko-pusu/redmine_issue_templates/releases)

Tagged version 0.1.4 is not working correctly under ruby 1.9x, related this issue:
https://github.com/akiko-pusu/redmine_issue_templates/issues/83

After I fixed this defect and it applied into master branch.
Could you please get the latest code from master branch, or download v0.1.4 from https://github.com/akiko-pusu/redmine_issue_templates/releases 
(I also just move v0.1.4’s tag to latest master branch)

**Comment by akiko-pusu** [comment]
Hi, @supar how is your current situation? Do you still need any help?

**Comment by supar** [comment]
No, still get error

I cloned mater from github, latest commit c422e4a36e04a

Log:
Rendered issues/show.html.erb within layouts/base (297.4ms)
Completed 500 Internal Server Error in 631.2ms

ActionView::Template::Error (/home/redmine/redmine/plugins/redmine_issue_templates/app/models/issue_template_setting.rb:26: syntax error, unexpected tLABEL, expecting ')'
    def apply_template_to_child_projects(project_id: nil)
                                                    ^
/home/redmine/redmine/plugins/redmine_issue_templates/app/models/issue_template_setting.rb:31: syntax error, unexpected tLABEL, expecting ')'
    def unapply_template_from_child_projects(project_id: nil)
                                                        ^
/home/redmine/redmine/plugins/redmine_issue_templates/app/models/issue_template_setting.rb:44: syntax error, unexpected keyword_end, expecting $end):
    1: <%= labelled_fields_for :issue, @issue do |f| %>
    2: <%= call_hook(:view_issues_form_details_top, { :issue => @issue, :form => f }) %>
    3:
    4: <% if @issue.safe_attribute? 'is_private' %>
    5: <p style="float:right; margin-right:1em;">

**Comment by akiko-pusu** [comment]
@supar 
Thanks for additional information.
This defect is because Ruby 1.9.x doesn't support named parameters.
I’m afraid it may not be possible for you to update ruby to 2.x for the time being, so I’m going to change method not to use named parameters as quick fix.

Pull request for workaround is here:
https://github.com/akiko-pusu/redmine_issue_templates/pull/94/files

I hope this PR will be effective, but I’ve done some code refactoring since v0.1.3, another defects may happen depending on the combination of ruby, rails, and Redmine.

**Comment by akiko-pusu** [comment]
I’ve just merged workaround into master branch and tagged v0.1.4.1.
https://github.com/akiko-pusu/redmine_issue_templates/releases/tag/v0.1.4.1

Hope this would be help for you.
If still have trouble, please let me know that have you already used older version of issue templates or not.
It seems your Redmine env is v2.x and Rails 3.x, now latest version of issue template may not be working correctly.
